### ISSUE TITLE
Data-last API proposal

### ISSUE THREAD

**Issue by jankoritak** [webscopeio/react-firestore-connect#3]
Due to current API, _connectFirestore_ component is not compose-friendly.

**Example:**
- Let's use [Ramda.js - Compose](https://ramdajs.com/docs/#compose) function for demonstration purposes

Current implementation:
- Wrapped component is not the last argument of the HOC
- Enforces following pattern 

```
const result = R.compose(
  HOC3,
  WrappedComponent => connectFirestore(
    (db, props, uid) => ({
      users: db.collection('names'),
    }),
    WrappedComponent,
    'once'
  ),
  HOC2,
  HOC1,
)(Component)
```

Refactor proposal:
- Change the API so that wrapped component is the last argument of _connectFirestore_
- Allows more convenient, declarative compose pattern

```
const result = R.compose(
  HOC3,
  connectFirestore(
    (db, props, uid) => ({
      users: db.collection('names'),
    }),
    'once'
  ),
  HOC2,
  HOC1,
)(Component)
```

Keep in mind this is a breaking API change.

**Comment by Olovorr** [comment]
Let's do this. I would still be glad to make 'once' optional parameter, so please keep that in mind while implementing. Feel free to start working on this 👼
