### ISSUE TITLE
UID is undefined

### ISSUE THREAD

**Issue by ymhr** [webscopeio/react-firestore-connect#7]
Even though my user is logged in, the `uid` is coming through as undefined. I wonder if there is another step I should be taking?

**Comment by Olovorr** [comment]
Hey @ymhr!
Couple of things come to my mind:
a) If you are trying to just console.log uid in the component, and not in the connect firestore itself, it will be undefined. Currently we are not passing uid to the component itself, we are sending it just as the argument in the function. So if you want to have uid in the component, you need to put `uid: uid` into connect firestore, i.e.: 
```
export default connectFirestore(
  (db, props, uid) => ({
    users: db.collection('names'), // You can get entire collection
    uid: uid,
  }),
)(Example)
```
But this can be easily changed so we send it to component by default, it is really easy.

b) If you are checking uid directly in connectFirestore, such as in this example:
```
export default connectFirestore(
  (db, props, uid) => {
    console.log('uid', uid);
    return ({
      users: db.collection('names'), // You can get entire collection
      uid: uid,
    })
  },
)(Example)
```
and it is undefined, I would check whether do you use initialiseFirebase with the correct firebase reference in the root of your project.

If this didn't answer your question, could you send me a code sample of your component?

**Comment by ymhr** [comment]
Thanks for the reply @Olovorr!

It's `b` for me - I cannot guarantee I was using it in the correct way, but I have a function where I initialise my firebase connection (just an import that's executed in my root file). I tried doing `initialiseFirebase` in there, but it had the same issue. I'll see if I can re-create the issue and send it over, I've removed the dependency from my library for now so I'll have to put it back.

**Comment by Olovorr** [comment]
@ymrh I will investigate this myself, we didn't run into this issue so far, but we are still using version 1.1.4 so it can be some regression. I will make project with version 2.0 and will try if I have this problem 🤔 

Thanks for reporting this 🙂

**Comment by ymhr** [comment]
@Olovorr yeah this was absolute user error - I was initialising it in the correct file, but in the wrong _location_ within that file! I was initialising it after firebase had been configured, but _before_ **firestore** had been configured. I didn't realise that the order was necessary until I looked at it with fresh eyes.

I'm going to close this issue, thanks for looking into it!

**Comment by Olovorr** [comment]
@ymhr No problem, great to know you solved your issue! 🙂And thanks for using the package, if you have any suggestions on improvements, feel free to create an issue. 👍
